### ISSUE TITLE
Tried to compile 

### ISSUE THREAD

**Issue by Shanker511** [HeyMaslo/companion-kit#5]
C:\Users\erwin\Downloads\companion-kit-master (1)\companion-kit-master>yarn all
yarn run v1.22.4
$ yarn && cd dashboard && yarn && cd ../mobile && yarn && cd ../server/functions && yarn && cd ../..
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "firebase-admin > @firebase/database > @firebase/auth-interop-types@0.1.4" has unmet peer dependency "@firebase/app-types@0.x".
[5/5] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.5", while you're on "1.22.4".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
[1/5] Validating package.json...
[2/5] Resolving packages...
error Package "" refers to a non-existing file '"C:\\Users\\erwin\\Downloads\\companion-kit-master (1)\\companion-kit-master\\mobile\\dependencies\\persona"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Shanker511** [comment]
C:\Users\erwin\Downloads\companion-kit-master (1)\companion-kit-master\mobile\dependencies>git clone git@github.com:HeyMaslo/maslo-persona.git persona && cd persona && git fetch --all && git checkout colors-config
Cloning into 'persona'...
The authenticity of host 'github.com (140.82.112.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.112.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by vitorbarros** [comment]
Hey, @Shanker511 these repositories are public, so you should not be getting this error.

You can take a look bellow

https://github.com/HeyMaslo/react-native-switch-pro
https://github.com/HeyMaslo/maslo-persona

You can also check the .gitmodules file and try to initiate it, like this

```bash
git clone --recursive git@github.com:HeyMaslo/companion-kit.git
```

or

```bash
git submodule update
```

Please let me know if you have any issues.
